version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: datazbiornix-db
    restart: always
    environment:
      POSTGRES_USER: datazbiornix
      POSTGRES_PASSWORD: datazbiornix_password
      POSTGRES_DB: datazbiornix
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

